# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |graphite|
  graphite.vm.box = "ubuntu/trusty64"
  graphite.vm.network :private_network, ip: "192.168.33.21"
  graphite.vm.network "forwarded_port", guest: 80, host: 8080
  graphite.vm.network "forwarded_port", guest: 2003, host: 2003

  graphite.vm.provision :shell, path: "bootstrap.sh"

  graphite.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

end
