# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |graphite|
  graphite.vm.box = "ubuntu/trusty64"
  graphite.vm.network :private_network, ip: "192.168.33.21"
  graphite.vm.network "forwarded_port", guest: 80, host: 8080
  graphite.vm.network "forwarded_port", guest: 2003, host: 2003

  graphite.vm.provision :shell, path: "bootstrap.sh"

  graphite.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

end
