# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |statsd|
  statsd.vm.box = "ubuntu/trusty64"
  statsd.vm.network :private_network, ip: "192.168.33.20"
  statsd.vm.network "forwarded_port", guest: 8125, host: 8125

  # nodejs startup script
  statsd.vm.provision "file", source: "./nodejs.conf", destination: "/home/vagrant/nodejs.conf"
  # installs node.js, downloads statsd, starts the service
  statsd.vm.provision :shell, path: "bootstrap.sh"

  statsd.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

end
