# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |statsd|
  statsd.vm.box = "ubuntu/trusty64"
  statsd.vm.network :private_network, ip: "192.168.33.20"
  statsd.vm.network "forwarded_port", guest: 8125, host: 8125

  # nodejs startup script
  statsd.vm.provision "file", source: "./nodejs.conf", destination: "/home/vagrant/nodejs.conf"
  # config to send rolled up metrics to 192.168.33.21, the graphite VM IP.
  statsd.vm.provision "file", source: "./config.js", destination: "/home/vagrant/config.js"
  # installs node.js, downloads statsd, starts the service
  statsd.vm.provision :shell, path: "bootstrap.sh"

  statsd.vm.provider "virtualbox" do |vb|
    vb.memory = 768
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

end
